name: CI-CD to GHCR

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때만 동작 (원하시는 방식으로 변경 가능)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # (선택) Node 환경 세팅 - npm install, 테스트 등 진행하려면
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      # 여기서 테스트 스크립트도 같이 실행 가능 (예: npm test)
      # - name: Run tests
      #   run: npm test

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # 이미지 이름 - ghcr.io/<OWNER>/<REPO_OR_IMAGE_NAME>:<TAG>
          # github.repository => "OWNER/REPO" 형식. 예) "myname/sse-service"
          # 아래 예시처럼 "sse-service"를 이미지명으로 쓸 경우:
          tags: ghcr.io/${{ github.repository }}/sse-service:latest

          # GHCR에 로그인
          # GitHub Actions의 GITHUB_TOKEN 활용
          # (repo Settings > Actions > General 에서 "Read and write" 권한으로 설정해야 함)
          load: false
          labels: |
            org.opencontainers.image.source=${{ github.repository }
          registry: ghcr.io
          # username: Defaults to github.actor if not set
          # password: GITHUB_TOKEN 이용
          # => build-push-action@v3가 자동으로 GITHUB_TOKEN을 사용하도록 해줌
